### ISSUE TITLE
Необработанные страницы ТЭЦ-4.xlsm (переименованный файл)

### ISSUE THREAD

**Issue by D1ffic00lt** [llitone/CHP-project#15]
# Задание
аналогичное #13 задание, работаем

# Чек-лист
- [ ] Панель_ПТО
- [ ] Панель_НСС
- [ ] Панель_МТ-1
- [ ] Панель_МТ-2
- [ ] Панель_МК-1
- [ ] Панель_МК-2
- [ ] ТА_3,4
- [ ] ТА_5
- [ ] ТА_6,7,8
- [ ] КА_5,6,7,8
- [ ] КА_9,10,11,12

**Comment by YuriyKarabintsev** [comment]
Панель ПТО в процессе. Нашёл некоторые формулы и определения.
